apiVersion: v1
kind: Service
metadata:
  name: mailserver
spec:
  type: LoadBalancer
  selector:
    app: mailserver
  ports:
    - name: tcp
      port: 25
      targetPort: 25
    - name: tcp1 
      port: 80
      targetPort: 4000
