apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailserver
spec:
  selector:
    matchLabels:
      app: mailserver
  template:
    metadata:
      labels:
        app: mailserver
    spec:
      containers:
      - name: mailserver
        image:  maildev/maildev:1.1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 25
        - containerPort: 80
