apiVersion: apps/v1
kind: Deployment
metadata:
  name: logserver
spec:
  selector:
    matchLabels:
      app: logserver
  template:
    metadata:
      labels:
        app: logserver
    spec:
      containers:
      - name: logserver
        image: datalust/seq:latest
        ports:
        - containerPort: 80
        env:
          - name: ACCEPT_EULA
            value: "Y"
