apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehiclemanagement
spec:
  selector:
    matchLabels:
      app: vehiclemanagement
  template:
    metadata:
      labels:
        app: vehiclemanagement
    spec:
      containers:
      - name: vehiclemanagement
        image: pitstop/vehiclemanagementapi:1.0
        ports:
        - containerPort: 5000
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
