apiVersion: apps/v1
kind: Deployment
metadata:
  name: customermanagement
spec:
  selector:
    matchLabels:
      app: customermanagement
  template:
    metadata:
      labels:
        app: customermanagement
    spec:
      containers:
      - name: customermanagement
        image: pitstop/customermanagementapi:1.0
        ports:
        - containerPort: 5100
