apiVersion: apps/v1
kind: Deployment
metadata:
  name: CustomerManagementAPI
spec:
  selector:
    matchLabels:
      app: CustomerManagement
  template:
    metadata:
      labels:
        app: CustomerManagement
    spec:
      containers:
      - name: CustomerManagementAPi
        image: pitstop/customermanagementapi:1.0
        ports:
        - containerPort: 5100
