apiVersion: apps/v1
kind: Deployment
metadata:
  name: WorkshopManagementAPI
spec:
  selector:
    matchLabels:
      app: WorkshopManagementAPI
  template:
    metadata:
      labels:
        app: WorkshopManagementAPI
    spec:
      containers:
      - name: WorkshopManagementAPI
        image: pitstop/workshopmanagementapi:1.0
        ports:
        - containerPort: 5200
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
