apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshopmanagement
spec:
  selector:
    matchLabels:
      app: workshopmanagement
  template:
    metadata:
      labels:
        app: workshopmanagement
    spec:
      containers:
      - name: workshopmanagement
        image: pitstop/workshopmanagementapi:1.0
        ports:
        - containerPort: 5200
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
