---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
  - port: 15672
    targetPort: 15672
  - port: 5672
    targetPort: 5672
---

apiVersion: v1
kind: Service
metadata:
  name: sqlserver
spec:
  selector:
    app: sqlserver
  ports:
  - protocol: TCP
    port: 1434
    targetPort: 1433


