apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  serviceName: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management-alpine
        volumeMounts:
        - name: rabbitmqdata
          mountPath: /var/lib/rabbitmq
        env:
        - name: RABBITMQ_CONFIG_FILE
          value: /etc/pitstop/rabbitmq.conf
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          #memory: '256mi'
          #cpu: '0.5'
          storage: 1Gi

        
          
